env: local

server:
  port: ${METADATA_PORT}

datasource:
  jdbcUrl: jdbc:postgresql://${DB_PG_IP}:${DB_PG_PORT}/kun
  username: ${DB_PG_USERNAME}
  password: ${DB_PG_PASSWORD}
  driverClassName: org.postgresql.Driver

flyway:
  locations: sql/
  table: flyway_kun_mt_schema_history
  baselineOnMigrate: true
  baselineVersion: 0

workflow:
  url: http://${WORKFLOW_HOST}:${WORKFLOW_PORT}
  cronExpr: 0 0 12 * * ?

rpc:
  registry: redis://${DB_REDIS_IP}:6379/
  port: ${METADATA_RPC_SERVICE_PORT}

kafka:
  bootstrapServers: 127.0.0.1:9092
  mceTopicName: kun-metadata-mce
  mseTopicName: kun-metadata-mse
  mceGroupId: 87f367957a9b49c48ce708fae38a158c
  mseGroupId: 18bf66dc2c4249baa45618c43fae51b5
  pushMode: off