
# workflow:
#   rules:
#     - changes:
#       - kun-metadata/*

verify-kun-data-discover-test:
  extends: .build-kun-data-discover
  stage: verify
  image: gradle:6.5.0-jdk8
  except:
    - master
    - release
    - production
    - tags
  allow_failure: false
  script:
    - ./gradlew check -p kun-data-discover

verify-kun-data-discover-sonar:
  extends: .build-kun-data-discover
  stage: verify
  image: mioyingtech/gradle-sonar:0.1-build
  except:
    - release
    - production
    - tags
  allow_failure: false
  script:
    - >
      if [ $CI_COMMIT_REF_NAME == "master" ]; then 
          ./gradlew sonarqube -p kun-data-discover -Dsonar.host.url=$SONAR_HOST -Dsonar.login=$SONAR_TOKEN -Dsonar.analysis.mode=publish -Dsonar.issuesReport.html.enable=true -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.projectKey=com.miotech:kun-data-discover -Dsonar.projectName='kun-data-discover';
      else ./gradlew sonarqube -p kun-data-discover -Dsonar.host.url=$SONAR_HOST -Dsonar.login=$SONAR_TOKEN -Dsonar.analysis.mode=preview -Dsonar.issuesReport.html.enable=true -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.projectKey=com.miotech:kun-data-discover -Dsonar.projectName='kun-data-discover';  
      fi

kun-data-discover-build:
  extends: 
    - .build-kun-data-discover
    - .only-deploy
  stage: build
  image: gradle:6.5.0-jdk8
  tags:
    - build
  script:
    - ./gradlew :kun-data-discover:bootJar
    - mkdir -p /builds/artifacts/kun-data-discover/${CI_COMMIT_REF_NAME}/
    - cp kun-data-discover/build/libs/*.jar /builds/artifacts/kun-data-discover/${CI_COMMIT_REF_NAME}/

kun-data-discover-push:
  extends: 
    - .build-kun-data-discover
    - .only-deploy
  image: mioyingtech/docker:latest
  stage: build-images
  tags:
    - docker-push
  script:
    - mkdir -p /builds/kun-data-discover/build/libs/
    - rsync -vzrtopg --progress -e ssh root@$CI_RUNNER_SERVER:/miotech/artifacts/kun-data-discover/${CI_COMMIT_REF_NAME}/ /builds/kun-data-discover/build/libs/
    - docker login -u $CI_BUILD_DOCKER_USER -p $CI_BUILD_TOKEN $CI_BUILD_DOCKER_URL
    - docker build -t ${CI_BUILD_DOCKER_URL}mioyingtech/kun-data-discovery:$CI_COMMIT_REF_NAME /builds/kun-data-discover/
    - docker push ${CI_BUILD_DOCKER_URL}mioyingtech/kun-data-discovery:$CI_COMMIT_REF_NAME
  only:
    changes:
      - kun-data-discover/*

kun-data-discover-set-tag:
  extends: .build-kun-data-discover
  stage: set-tag
  tags:
    - build
  image: mioyingtech/python-gitlab:0.1-build
  script:
    - python /tmp/tag.py --projectId $CI_PROJECT_ID --branchName $CI_COMMIT_REF_NAME --privateToken $CI_GITLAB_TOKEN --gitlabUrl $GITLAB_URL --serviceName kun-data-discover
  only:
    - production
      
kun-data-discover-set-tag-hotfix:
  extends: .build-kun-data-discover
  stage: set-tag
  tags:
    - build
  image: mioyingtech/python-gitlab:0.1-build
  script:
    - python /tmp/tag.py --projectId $CI_PROJECT_ID --branchName $CI_COMMIT_REF_NAME --privateToken $CI_GITLAB_TOKEN --gitlabUrl $GITLAB_URL --serviceName kun-data-discover
  only:
    - /^HOTFIX+.*/
  when: manual

kun-data-discover-save-tag:
  extends: .build-kun-data-discover
  stage: save-tag
  tags:
    - build
  image: mioyingtech/python-gitlab:0.1-build
  only:
    - tags
  script:
    - python /tmp/saveTag.py --appName=kun-data-discover --tag=${CI_COMMIT_REF_NAME}
  allow_failure: true